import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./(components)/utils/ThemeProvider";
import Navbar from "./(components)/nav/NavBar";
import BackToTop from "./(components)/utils/BackToTop";

// Jakarta Font Setup
const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jakarta.variable} antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <BackToTop />
        </Providers>
      </body>
    </html>
  );
}
